homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

json:
    path: /json/{name}
    defaults: { _controller: AppBundle:JSON:show }

contact-us:
    path: /contact-us/{slug}
    defaults: { _controller: AppBundle:ContactUs:show, slug: 'index' }

# Everything else
page:
    path: /{slug}
    defaults: { _controller: AppBundle:Default:page }
