#app:
#  resource: "@AppBundle/Controller/"
#  type:     annotation

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

page:
  path: /{slug}
  defaults: { _controller: AppBundle:Default:page }
